services:
  webapp-boilerplate:
    environment:
    image: tomcat:9-jdk21-temurin-jammy
    container_name: webapp-boilerplate
    network_mode: host
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - ./build/libs/:/usr/local/tomcat/webapps/
