# this file is not in use
# it requires an hosted sonarqube server if you want to self-host
name: sonarqube
on:
  push:
    branches:
      - dev
  # should separate this
  pull_request:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        default: "warning"
      tags:
        description: "Test scenario tags"
jobs:
  deploy:
    name: sonarqube
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      name: SonarQube Integration
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            # Disabling shallow clone is recommended for improving relevancy of reporting
            fetch-depth: 0
        - name: SonarQube Scan
          uses: sonarsource/sonarqube-scan-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Sonar Token generated
            SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }} # example URL (https://website.com/)
