on:
  workflow_dispatch: {}
  # pull_request:
  #   branches: ["dev"]
  push:
    branches:
      - dev
  schedule:
    - cron: 11 2 * * *
name: Semgrep Workflow
jobs:
  semgrep:
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    if: github.event.pull_request.draft == false && github.actor != 'dependabot[bot]'
    name: Semgrep Job
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep@sha256:550dfdac1ec5d4a757d1c2ac0197a6360ef3ac8e3d0a804731eab07242e91b4c
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - run: semgrep ci --sarif > semgrep.sarif
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@2e230e8fe0ad3a14a340ad0815ddb96d599d2aff # v3
        with:
          sarif_file: semgrep.sarif
        if: always()
