# IMP: snyk token can't be used from forks, so PRs from forks will fail
name: Snyk Security Scan Workflow
on:
  # pull_request:
  #   branches: ["dev"]
  push:
    branches:
      - dev
      - app-start-test
permissions:
  contents: read
jobs:
  snyk:
    name: Snyk Security Scan Job
    permissions:
      security-events: write
      packages: read
      contents: read
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Set up Snyk CLI to check for security issues
        uses: snyk/actions/setup@d406fd286b663eb8c6f8adcced4f7bcd199c0a3f
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: login to snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}
      - name: run snyk open source
        run: snyk test --all-projects --sarif > snyk-os.sarif || true
      # init scanning for vulnerabilities
      - name: run snyk container
        run: snyk container test ${{ env.TEST_TAG }} --file=Dockerfile --sarif > snyk-container.sarif || true
      # - name: Run Snyk to check Docker image for vulnerabilities
      #   # Snyk can be used to break the build when it detects vulnerabilities.
      #   # In this case we want to upload the issues to GitHub Code Scanning
      #   continue-on-error: true
      #   uses: snyk/actions/docker@master
      #   # FIXME: sarif output doesn't work
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      #   with:
      #     image: ${{ env.TEST_TAG }}
      #     # sarif: true # default
      #     args: --file=Dockerfile
      #     # - name: Upload result to GitHub Code Scanning
      #     #   uses: github/codeql-action/upload-sarif@v3
      #     #   with:
      #     #     sarif_file: snyk.sarif
      - name: Snyk Code test
        run: snyk code test --sarif > snyk-code.sarif  || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3
        with:
          sarif_file: snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3
        with:
          sarif_file: snyk-os.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@f079b8493333aace61c81488f8bd40919487bd9f # v3
        with:
          sarif_file: snyk-container.sarif
